name: square-well-emulators-env

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.10.8
  - numpy=1.23.5
  - scipy=1.9.3
  - pandas=1.5.2
  - seaborn=0.12.1
  - matplotlib=3.6.2
  - matplotlib-inline>=0.1.6
  - notebook=6.5.2
  - ipython=8.7.0
  - nbconvert=7.2.5
  - pip=22.3.1
